models/Competition.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "competition".
 *
 * @property integer $competition_id
 * @property string $name
 * @property string $description
 * @property string $date_of_create
 */
class Competition extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'competition';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description'], 'required'],
            [['description'], 'string'],
            [['date_of_create'], 'safe'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'competition_id' => 'Competition ID',
            'name' => 'Name',
            'description' => 'Description',
            'date_of_create' => 'Date Of Create',
        ];
    }

    public static function getCountCompetition()
    {
        return self::find()
            ->count();
    }

    public static function getNameCompetition($competition_id)
    {
        $nameCompetition = self::find()
            ->asArray()
            ->select(['name'])
            ->where(['competition_id' => $competition_id])
            ->one();
        return array_shift($nameCompetition);
    }

    public static function getAllCompetition()
    {
        return self::find()
            ->asArray()
            ->select('*')
            ->orderBy(['competition_id' => SORT_DESC])
            ->all();
    }
}

controllers/CompetitionController.php
<?php

namespace app\controllers;

use app\models\Competition;
use yii\data\Pagination;
use app\models\CompetitionDocuments;

class CompetitionController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $listCompetition = Competition::getAllCompetition();
        $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => Competition::getCountCompetition(),
        ]);

        return $this->render('index',[
            'listCompetition' => $listCompetition,
            'pagination' => $pagination,
        ]);
    }

    public function actionCompetitionDocuments($competition_id)
    {
        $listDocuments = CompetitionDocuments::getAllDocuments($competition_id);
        $nameCompetition = Competition::getNameCompetition($competition_id);

        return $this->render('competition-documents',[
            'listDocuments' => $listDocuments,
            'nameCompetition' => $nameCompetition,
        ]);
    }

}

views/competition/competition-documents.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;


$this->title = $nameCompetition;
$this->params['breadcrumbs'][] = ['label' => 'Змагання', 'url' => ['competition/index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<h1><?= Html::encode($this->title) ?></h1>

<p>
<?php if(!empty($listDocuments)): ?>
    <?php foreach($listDocuments as $key): ?>
    <div class="documents">
        <?php

        $name_file;
        if(!empty($key['name_fille'])){
            $name_file = PATH_DOCUMENT_FOR_COMPETITION_SHOW.$key['name_fille'];
            $class = 'active';
            $alert = 'button-active';
        } else {
            $name_file = '#';
            $class = 'disabled';
            $alert = 'button-disabled';;
        }
        ?>
        <div class="text-documents">
            <h3><?= Html::encode($key['name']); ?></h3>
            <p><?= nl2br($key['description']); ?></p>
        </div>
        <div class="button-documents">
            <button class="<?= $alert ?>"><a href="<?= $name_file ?>" class="<?= $class ?>" target="_blank" >Показати</a></button>
            <button class="<?= $alert ?>"><a href="<?= $name_file ?>" class="<?= $class ?>" download>Завантажити</a></button>
        </div>
    </div>
    <div class="documents-date">
        <p>Дата створення - <?= $key['date_of_create']; ?></p>
    </div>
<?php endforeach; ?>
<?php endif; ?>

</p>

views/competition/index.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\widgets\LinkPager;

$this->title = 'Змагання';
$this->params['breadcrumbs'][] = $this->title;


?>
<h1><?= $this->title ?></h1>

<p>
<?php if(!empty($listCompetition)): ?>
    <?php foreach($listCompetition as $key): ?>
    <div class="documents">
        <div class="text-documents">
            <h3><?= Html::encode($key['name']); ?></h3>
        </div>
        <div class="button-documents">
            <button><a href="<?= Yii::$app->urlManager->createUrl(['competition/competition-documents', 'competition_id' => $key['competition_id']]); ?>" cursor="default" >Переглянути деталі</a></button>
        </div>
    </div>

    <div class="documents-date">
        <p>Дата створення - <?= $key['date_of_create']; ?></p>
    </div>
<?php endforeach; ?>
</p>
<?= LinkPager::widget(['pagination' => $pagination]) ?>
<?php endif; ?>